# Generated by Django 5.0.2 on 2024-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0003_generatedcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
